version: '3.7'

services:
  fastapi:
    build: .
    container_name: fastapi
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis
  worker:
    build: .
    container_name: worker
    entrypoint: [ 'celery', '-A', 'app.celery_worker', 'worker', '-l', 'info' ]
    depends_on:
      - redis
  flower:
    build: .
    container_name: flower
    command: [ 'celery', '--broker=redis://redis:6379', 'flower', '--port=5555' ]
    ports:
      - 5557:5555
    depends_on:
      - redis